import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;

public class BedRoom extends javax.swing.JFrame {


    private static Timer timer;
    /**
     * Creates new form BedRoom
     */boolean keyObtained = false;

    public BedRoom() {
        initComponents();
        setTitle("BedRoom");
        setPreferredSize(new java.awt.Dimension(950, 580));
        setResizable(false);
        setLocationRelativeTo(null);
        lblbg.add(btnGoLiv);
        lblbg.add(btnNotes);
        lblbg.add(btnTablet);
        lblbg.add(btnKey);

        btnKey.setOpaque(false);
        btnKey.setContentAreaFilled(false);
        btnKey.setBorderPainted(false);
        btnKey.setBounds(200, 180, 50, 50);
        btnKey.setVisible(false);

        btnTablet.setOpaque(false);
        btnTablet.setContentAreaFilled(false);
        btnTablet.setBorderPainted(false);
        btnTablet.setBounds(230, 350, 70, 50);

        btnGoLiv.setOpaque(false);
        btnGoLiv.setContentAreaFilled(false);
        btnGoLiv.setBorderPainted(false);
        btnGoLiv.setBounds(10, 250, 70, 50);

        btnNotes.setOpaque(false);
        btnNotes.setContentAreaFilled(false);
        btnNotes.setBorderPainted(false);
        btnNotes.setBounds(85, 260, 70, 50);

       /* timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (LoadingScr.tm.getrTime()) {
                    //lblbg.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(BedRoom.class.getResource("/image/died.png"))));
                    //MainMenu m = new MainMenu();
                    dispose();
                    timer.stop();
                    GameOver g = new GameOver();
                    g.setVisible(true);
                }
            }
        });
        timer.start();*/

        if(Login.acc.getIsTabletUnlocked()==true){
            lblbg.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(BedRoom.class.getResource("/image/Bedroomv2.png"))));
            if(keyObtained == false && Login.acc.getIsCRUnlocked()==false)
                 btnKey.setVisible(true);
            else
                btnKey.setVisible(false);
        }
        lineReader.gameOver(this);
    }

    // Your other methods and variables...

    // Main method and other UI-related methods...




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnGoLiv = new javax.swing.JButton();
        btnKey = new javax.swing.JButton();
        btnTablet = new javax.swing.JButton();
        btnNotes = new javax.swing.JButton();
        lblbg = new javax.swing.JLabel();

        btnGoLiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goLiv2.png"))); // NOI18N
        btnGoLiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoLiv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnGoLivFocusGained(evt);
            }
        });
        btnGoLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLivActionPerformed(evt);
            }
        });

        btnKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/key.png"))); // NOI18N
        btnKey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActionPerformed(evt);
            }
        });

        btnTablet.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        btnTablet.setForeground(new java.awt.Color(255, 255, 255));
        btnTablet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tab.png"))); // NOI18N
        btnTablet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabletActionPerformed(evt);
            }
        });

        btnNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dec.png"))); // NOI18N
        btnNotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bedroom.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(lblbg)
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btnGoLivActionPerformed(java.awt.event.ActionEvent evt) {
        LivingRoom l = new LivingRoom();
        setVisible(false);
        l.setVisible(rootPaneCheckingEnabled);
    }

    private void btnGoLivFocusGained(java.awt.event.FocusEvent evt) {
        btnGoLiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goLiv2v2.png")));            // TODO add your handling code here:
    }

    private void btnNotesActionPerformed(java.awt.event.ActionEvent evt) {
        Notes n = new Notes();
        n.setVisible(true);
    }


    private void btnTabletActionPerformed(java.awt.event.ActionEvent evt) {
        if(Login.acc.getIsTabletUnlocked()) {
            Tablet t = new Tablet();
            t.setVisible(true);
        }else{
            Minigame m = new Minigame();
            m.setVisible(true);
        }
    }
    public static void setBg(){
        if(lblbg!=null&& Login.acc.getIsTabletUnlocked()==true) {
            lblbg.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(BedRoom.class.getResource("/image/Bedroomv2.png"))));
            btnKey.setVisible(true);
        }
    }

    private void btnKeyActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null,"The Room next to the Kitchen has been Unlocked");
        btnKey.setVisible(false);
        keyObtained=true;
        Login.acc.setIsCRUnlocked();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BedRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BedRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BedRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BedRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BedRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnGoLiv;
    private static javax.swing.JButton btnKey;
    private javax.swing.JButton btnNotes;
    private javax.swing.JButton btnTablet;
    private static javax.swing.JLabel lblbg;
    // End of variables declaration
}