
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        setTitle("Gamover");
        setPreferredSize(new java.awt.Dimension(950, 580));
        setResizable(false);
        setLocationRelativeTo(null);
        lblbg.add(btnRetry);
        lblbg.add(btnGoBack);

        btnRetry.setOpaque(false);
        btnRetry.setContentAreaFilled(false);
        btnRetry.setBorderPainted(false);
        btnRetry.setBounds(250, 320, 250, 50);

        btnGoBack.setOpaque(false);
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setBorderPainted(false);
        btnGoBack.setBounds(430, 320, 250, 50);
        MusicPlayer.playDie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnGoBack = new javax.swing.JButton();
        btnRetry = new javax.swing.JButton();
        lblbg = new javax.swing.JLabel();

        btnGoBack.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Main Menu");
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        btnRetry.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        btnRetry.setForeground(new java.awt.Color(255, 255, 255));
        btnRetry.setText("Try Again");
        btnRetry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/died.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblbg)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(lblbg)
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {
        MusicPlayer.stopMusic();
        setVisible(false);
        dispose();
        MainMenu x = new MainMenu();
        x.setVisible(true);
    }

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {
        MusicPlayer.stopMusic();
        MusicPlayer.playP();
        dispose();
        setVisible(false);
        LoadingScr.tm.reset();
        Login.acc.reset();
        LivingRoom l  = new LivingRoom();
        l.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnRetry;
    private javax.swing.JLabel lblbg;
    // End of variables declaration
}
