import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Kitchen extends javax.swing.JFrame {
    Connection con; //variable for databse connection
    Statement st;
    private static Timer timer;


    public Kitchen() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(950, 580));
        setResizable(false);
        setLocationRelativeTo(null);
      /*  timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (LoadingScr.tm.getrTime()) {
                    //lblbg.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(BedRoom.class.getResource("/image/died.png"))));
                    //MainMenu m = new MainMenu();

                    dispose();
                    timer.stop();

                    GameOver g = new GameOver();
                    g.setVisible(true);
                }
            }
        });
        timer.start();*/
        lblbg.add(btnGoLiv);
        lblbg.add(btnGoCR);
        lblbg.add(btnToDoList);
        lblbg.add(btnBday);

        btnGoCR.setOpaque(false);
        btnGoCR.setContentAreaFilled(false);
        btnGoCR.setBorderPainted(false);
        btnGoCR.setBounds(10, 250, 70, 50);

        btnToDoList.setOpaque(false);
        btnToDoList.setContentAreaFilled(false);
        btnToDoList.setBorderPainted(false);
        btnToDoList.setBounds(875, 190, 50, 50);


        btnBday.setOpaque(false);
        btnBday.setContentAreaFilled(false);
        btnBday.setBorderPainted(false);
        btnBday.setBounds(250, 190, 50, 50);

        btnGoLiv.setOpaque(false);
        btnGoLiv.setContentAreaFilled(false);
        btnGoLiv.setBorderPainted(false);
        btnGoLiv.setBounds(870, 250, 70, 50);
       // lineReader.gameOver(this);

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnGoLiv = new javax.swing.JButton();
        btnGoCR = new javax.swing.JButton();
        btnToDoList = new javax.swing.JButton();
        btnBday = new javax.swing.JButton();
        lblbg = new javax.swing.JLabel();

        btnGoLiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goLiv.png"))); // NOI18N
        btnGoLiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoLiv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnGoLivAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnGoLiv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnGoLivFocusGained(evt);
            }
        });
        btnGoLiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoLivMouseClicked(evt);
            }
        });
        btnGoLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLivActionPerformed(evt);
            }
        });
        btnGoLiv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGoLivKeyPressed(evt);
            }
        });
        btnGoLiv.getAccessibleContext().setAccessibleDescription("");

        btnGoCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goCrLocked.png"))); // NOI18N
        btnGoCR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnGoCRFocusGained(evt);
            }
        });
        btnGoCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoCRActionPerformed(evt);
            }
        });

        btnToDoList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/toDo.png"))); // NOI18N
        btnToDoList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToDoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToDoListActionPerformed(evt);
            }
        });

        btnBday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bday.png"))); // NOI18N
        btnBday.setToolTipText("");
        btnBday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBdayActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kitchen.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(lblbg)
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblbg)
        );

        pack();
    }// </editor-fold>

    private void btnGoLivAncestorAdded(javax.swing.event.AncestorEvent evt) {
        // TODO add your handling code here:
    }

    private void btnGoLivActionPerformed(java.awt.event.ActionEvent evt) {
        LivingRoom l = new LivingRoom();
        setVisible(false);
        l.setVisible(true);
    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void btnGoLivKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void btnGoLivMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btnGoLivFocusGained(java.awt.event.FocusEvent evt) {
        btnGoLiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goLiv_v2.png")));        // TODO add your handling code here:
    }


    private void btnGoCRFocusGained(java.awt.event.FocusEvent evt) {
        if(Login.acc.getIsCRUnlocked()==false) {
            btnGoCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goCrLockedv2.png")));
        }else
            btnGoCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goCRv2.png")));
    }

    private void btnToDoListActionPerformed(java.awt.event.ActionEvent evt) {
        ToDoList t = new ToDoList();
        t.setVisible(true);
    }

    private void btnBdayActionPerformed(java.awt.event.ActionEvent evt) {
        Bday b = new Bday();
        b.setVisible(true);
    }

    private void btnGoCRActionPerformed(java.awt.event.ActionEvent evt) {
        if(Login.acc.getIsCRUnlocked()==false){
            JOptionPane.showMessageDialog(null,"Room Locked");
        }else{
            dispose();
            EndScene s = new EndScene();
            s.setVisible(true);
            LoadingScr.tm.stopEvent();
            InsertScore();

        }

    }
    public void InsertScore() {
        try {
            // Establish database connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acccos", "root", ""); // Database connection parameters

            // SQL query to update the score for the current user
            String sql1 = "UPDATE acc SET time='" + LoadingScr.tm.getTotal() + "' WHERE userName = '" + Login.acc.getUserName() + "' AND password = '" + Login.acc.getPassword() + "'";
            st = con.createStatement();

            // Execute the update query
            int rowsAffected = st.executeUpdate(sql1);
            if (rowsAffected > 0) {
                System.out.println("Score updated successfully!");
            } else {
                System.out.println("No rows updated. User not found or no change in score.");
            }

            // Close the Statement and Connection
            st.close();
            con.close();
        } catch (ClassNotFoundException | SQLException ex) {
            // Handle any exceptions
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    public static void setBtn(){
        if(btnGoCR!=null)
            btnGoCR.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(Kitchen.class.getResource("/image/goCR.png"))));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

               new Kitchen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnBday;
    private static javax.swing.JButton btnGoCR;
    private javax.swing.JButton btnGoLiv;
    private javax.swing.JButton btnToDoList;
    private javax.swing.JLabel lblbg;
    // End of variables declaration
}
